### ISSUE TITLE
Attempt refactor of Doit-based code in jupyter_accessibility

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/jupyter-a11y-testing#13]
The Python code that Tony wrote under `jupyter_accessibility` directory is on object-oriented wrapper around Doit.py.

My goal is to try to refactor that code to look more like conventional Doit scripts, for example, [the dodo.py file that Nick wrote in jupyter/accessibility](https://github.com/jupyter/accessibility/blob/main/pa11y-jupyter/dodo.py).

**Comment by gabalafou** [comment]
I'm behind on this task. I spent Friday going through the entire doit.py docs. Now I'm tackling the actual code in the repo.

**Comment by trallard** [comment]
From the meeting on 01 Sept - we decided to abandon this route at least for now
